spring.application.name=visa

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/visa_db
spring.datasource.username=postgres
spring.datasource.password=tsila
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
